server:
  port: 8084

spring:
  application:
    name: raceflow-session-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/sessions
    username: ${DB_USER:raceflow}
    password: ${DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: local
